---
apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: ops-manager
spec:
  replicas: 1
  version: 4.2.4
  adminCredentials: ops-manager-admin-secret

  # optional, disabled by default. Creates an additional service to make Ops Manager reachable from
  # outside of the Kubernetes cluster.
  externalConnectivity:
    # LoadBalancer|NodePort
    type: NodePort
    # optional, corresponds to nodePort port
    port: 30100

  applicationDatabase:
    members: 3
    version: 4.2.0
    persistent: true
  backup:
    enabled: true
    podSpec:
      cpuRequests: '0.50'
      memoryRequests: 300M
