---
apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: ops-manager-external
spec:
  replicas: 1
  version: 4.2.12
  adminCredentials: ops-manager-admin-secret

  # configuration:
  #   # set this property to allow Ops Manager to manage deployments outside of
  #   # Kubernetes cluster. This must be equal to an externally connectible DNS
  #   mms.centralUrl: http://

  # optional. Disabled by default. Creates an additional service to make Ops Manager reachable from
  # outside of the Kubernetes cluster.
  externalConnectivity:
    # LoadBalancer|NodePort
    type: NodePort
    # optional. Corresponds to NodePort port
    port: 30100

  applicationDatabase:
    members: 3
    version: 4.2.6-ent
    persistent: true
  backup:
    enabled: false
