---
apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: ops-manager
spec:
  version: 4.2.3-operator1.4.0
  adminCredentials: ops-manager-admin-secret
  configuration:
    mms.fromEmailAddr: "admin@thecompany.com"

  applicationDatabase:
    members: 3
    version: 4.2.0
    persistent: true
    type: ReplicaSet
    podSpec:
      cpu: '0.25'
