---
apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
  namespace: mongodb
data:
  projectName: K8sDemo
  baseUrl: http://ops-manager-svc.mongodb.svc.cluster.local:8080
  sslRequireValidMMSServerCertificates: 'false'
