---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-project
  namespace: mongodb
data:
  projectName: "DemoK8S"
  orgId: "5e588dc99b9267027e90019c"
  baseUrl: "https://ec2-13-211-255-87.ap-southeast-2.compute.amazonaws.com:8443"
  sslRequireValidMMSServerCertificates: 'false'
  sslMMSCAConfigMap: mms-svr-ca
