#
# This is a minimal config. To see all the options available, refer to the
# "extended" directory
#
---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: my-replica-set
spec:
  members: 3
  version: 4.2.1-ent
  type: ReplicaSet

  opsManager:
    configMapRef:
      name: my-project
  credentials: ops-manager-external-admin-key

  persistent: false

  podSpec:
    podTemplate:
      spec:
        initContainers:
        - name: "apply-sysctl-test"
          image: "busybox:latest"
          securityContext:
            privileged: true
          command: ["sysctl", "-w", "net.ipv4.tcp_keepalive_time=120"]
