#
# This is a minimal config. To see all the options available, refer to the
# "extended" directory
#
---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: my-replica-set
spec:
  members: 3
  version: 4.2.1-ent
  type: ReplicaSet

  opsManager:
    configMapRef:
      name: myconfigmap
  credentials: ops-manager-admin-key

  security:
    # tls:
    #   enabled: true
    authentication:
      enabled: true
      modes: ["SCRAM"]

      # modes: ["SCRAM", "X509"]
      # internalCluster: "X509"

  persistent: false
